<footer>
<div id="footer">
	COMP 1950 Project Designed by TeamOne 2012 Copyright &copy; All Rights Reserved.
</div>	<!-- footer div -->	
<div id="validators">
	<a href="http://validator.w3.org/check?uri=referer" class='validator'> 
		<img style="border-style:none" width="88" height="31" src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid HTML5"/>
	</a>
	<a href="http://jigsaw.w3.org/css-validator/check/referer" class='validator'> 
		<img style="border-style:none" width="88" height="31" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!"/>
	</a>
</div>
</footer>