<header id="main-header">
	<div id="search">
	    <!--
		<form method="get" action="#">
			<input type="text" name="search" size="31" maxlength="255" value="" />
			<input type="submit" value="Search" />
		</form>	
		-->
        <form class="freefind_search" action="http://search.freefind.com/find.html" method="get" accept-charset="utf-8">
            <input type="hidden" name="si" value="5308812">
            <input type="hidden" name="pid" value="r">
            <input type="hidden" name="n" value="0">
            <input type="hidden" name="_charset_" value="">
            <input type="hidden" name="bcd" value="&#247;">
            <input type="text" name="query" size="20" maxlength="255" value="" >
            <input type="submit" id="search-button" value="Search">
        </form>		
	</div> 
	<div id="heading">
		<h1>COMP1950</h1>
		<p>Intermediate Web Design and Development</p>
	</div>
</header>
<div id="logo">
	<a href="index.shtml"><img src="image/bcit-logo.jpg" alt="bcit logo" /></a>
</div>