<nav id="right-nav">
    <h2>Contents</h2>
    <ul>
        <li class="menu-item">
            <a href="http://comp1950team1.tumblr.com/">
				<span class="menu-item-title">Blog</span><br/>
			</a>
        </a>
    </ul>
    <h2>Lectures</h2>
	<ul id="accordion" class="menu">
		<li class="menu-item" id="lecture01">
			<a href="index.shtml">
				<span class="menu-item-title">01 Home & Introduction</span><br/>
                <span class="menu-item-desc">Introductions, First Assignment</span>
			</a>
		</li>
		<ul class="submenu">
			<li class="subitem"><a href="index.shtml#about">about (outline, assignments, etc)</a></li>
			<li class="subitem"><a href="index.shtml#intro-you-me">introductions</a></li>
			<li class="subitem"><a href="index.shtml#webspace-ftp">web space</a></li>
			<li class="subitem"><a href="index.shtml#expectation">expectations &amp; reminders</a></li>
			<li class="subitem"><a href="index.shtml#assignment">today's assignment</a></li>        
		</ul>
		<li class="inactive">02 | tools &amp; standards</li>
		<li class="inactive">03 | HTML 5 &amp; SEO</li>
		<li class="menu-item" id="lecture04">
			<a href="lecture04.shtml">
				<span class="menu-item-title">04 CSS Concepts</span><br/>
                <span class="menu-item-desc">Selectors, Specificity, Measurements</span>
			</a>
		</li>
		<ul class="submenu">
			<li class="subitem"><a href="lecture04.shtml#review-html5-assignment">Review HTML5 assignment</a></li>
			<li class="subitem"><a href="lecture04.shtml#markup-quiz">Markup Quiz</a></li>    
			<li class="subitem"><a href="lecture04.shtml#css-concepts">CSS Concepts</a></li>
			<li class="subitem"><a href="lecture04.shtml#exercises">Exercises</a></li>
			<li class="subitem"><a href="lecture04.shtml#specificity">Specificity</a></li>
			<li class="subitem"><a href="lecture04.shtml#measurements">Measurements</a></li>
		</ul>
		<li class="inactive">05 | more css</li>
		<li class="inactive">06 | CSS and SSIs</li>
		<li class="inactive">07 | template development</li>
		<li class="inactive">08 | more templating</li>
		<li class="inactive">09 | methodology</li>    
		<li class="inactive">10 | jQuery / Git</li>
	</ul>
</nav>
