<nav id="right-nav">
    <h2>Contents</h2>
    <ul>
        <li class="menu-item">
            <div class="menu-item-heading">
                <a href="http://comp1950team1.tumblr.com/">
                    <span class="menu-item-title">Blog</span><br/>
                </a>
            </div>
        </li>
    </ul>
    <h2>Lectures</h2>
	<ul id="accordion" class="menu">
		<li id="lecture01" class="menu-item">
            <div class="menu-item-heading">
                <a href="index.shtml">
                    <span class="menu-item-title">01 Home &amp; Introduction</span><br />
                    <span class="menu-item-desc">Introductions, First Assignment</span>
                </a>
            </div>
            <ul class="submenu">
                <li class="subitem"><a href="index.shtml#about">about (outline, assignments, etc)</a></li>
                <li class="subitem"><a href="index.shtml#intro-you-me">introductions</a></li>
                <li class="subitem"><a href="index.shtml#webspace-ftp">web space</a></li>
                <li class="subitem"><a href="index.shtml#expectation">expectations &amp; reminders</a></li>
                <li class="subitem"><a href="index.shtml#assignment">today's assignment</a></li>        
            </ul>
		</li>
		<li class="inactive">
            <span class="menu-item-title">02 Tools &amp; Standards</span><br />
            <span class="menu-item-desc">Browser Tools, Semantics, XHTML</span>
        </li>
		<li class="inactive">
            <span class="menu-item-title">03 HTML 5 &amp; SEO</span><br />
            <span class="menu-item-desc">SEO Basics, History of MLs</span>
        </li>
		<li id="lecture04" class="menu-item">
            <div class="menu-item-heading">
                <a href="lecture04.shtml">
                    <span class="menu-item-title">04 CSS Concepts</span><br />
                    <span class="menu-item-desc">Selectors, Specificity, Measurements</span>
                </a>
            </div>
            <ul class="submenu">
                <li class="subitem"><a href="lecture04.shtml#review-html5-assignment">Review HTML5 assignment</a></li>
                <li class="subitem"><a href="lecture04.shtml#css-concepts">CSS Concepts</a></li>
                <li class="subitem"><a href="lecture04.shtml#exercises">Exercises</a></li>
                <li class="subitem"><a href="lecture04.shtml#specificity">Specificity</a></li>
                <li class="subitem"><a href="lecture04.shtml#measurements">Measurements</a></li>
                <li class="subitem"><a href="lecture04.shtml#homework">Homework</a></li>			
            </ul>
		</li>

		<li class="inactive">
            <span class="menu-item-title">05 More CSS</span><br />
            <span class="menu-item-desc">Resets, Layouts, Media Queries</span>
        </li>
		<li class="inactive">
            <span class="menu-item-title">06 CSS and SSIs</span><br />
            <span class="menu-item-desc">CSS Review, SSI Introduction</span>
        </li>
		<li class="inactive">
            <span class="menu-item-title">07 Template Development</span><br />
            <span class="menu-item-desc">SSI Review, Tumblr Templates</span>
        </li>
		<li class="inactive"><span class="menu-item-title">08 More Templating</span></li>
		<li class="inactive"><span class="menu-item-title">09 Methodology</span></li>    
		<li class="inactive"><span class="menu-item-title">10 jQuery / Git</span></li>
	</ul>
    <h2>Contact</h2>
    <ul>
        <li class="menu-item">
            <div class="menu-item-heading">
                <a href="mailto:acalder1@my.bcit.ca">
                    <span class="menu-item-title">Alistair Calder</span><br/>
                </a>
            </div>
        </li>
    </ul>
    <h2>Associated Links</h2>
    <ul>
        <li class="menu-item">
            <div class="menu-item-heading">
                <a href="http://my.bcit.ca/">
                    <span class="menu-item-title">myBCIT</span><br/>
                </a>
            </div>
        </li>
        <li class="menu-item">
            <div class="menu-item-heading">
                <a href="http://www.bcit.ca/">
                    <span class="menu-item-title">BCIT</span><br/>
                </a>
            </div>
        </li>
        <li class="menu-item">
            <div class="menu-item-heading">
                <a href="http://www.computing.bcit.ca/">
                    <span class="menu-item-title">BCIT Computing</span><br/>
                </a>
            </div>
        </li>
        <li class="menu-item">
            <div class="menu-item-heading">
                <a href="http://www.alistair.com/">
                    <span class="menu-item-title">alistair.com</span><br/>
                </a>
            </div>
        </li>
    </ul>
</nav>
