<nav id="right-nav">
    <h2>Lectures</h2>
	<ul id="accordion" class="menu">
		<li class="menu-item">
			<a href="#">
				<span class="menu-item-title">01 Home & Introduction</span><br/>
                <span class="menu-item-desc">Introductions, First Assignment</span>
			</a>
		</li>
		<ul class="submenu">
			<li class="subitem"><a href="#">about (outline, assignments, etc)</a></li>
			<li class="subitem"><a href="#">introductions</a></li>
			<li class="subitem"><a href="#">web space</a></li>
			<li class="subitem"><a href="#">expectations &amp; reminders</a></li>
			<li class="subitem"><a href="#">web space</a></li>
			<li class="subitem"><a href="#">today's assignment</a></li>        
		</ul>
		<li class="inactive">02 | tools &amp; standards</li>
		<li class="inactive">03 | HTML 5 &amp; SEO</li>
		<li class="menu-item">
			<a href="#">
				<span class="menu-item-title">04 CSS Concepts</span><br/>
                <span class="menu-item-desc">Selectors, Specificity, Measurements</span>
			</a>
		</li>
		<ul class="submenu">
			<li class="subitem"><a href="#">Review HTML5 assignment</a></li>
			<li class="subitem"><a href="#">Markup Quiz</a></li>    
			<li class="subitem"><a href="#">CSS Concepts</a></li>
			<li class="subitem"><a href="#">Exercises</a></li>
			<li class="subitem"><a href="#">Specificity</a></li>
			<li class="subitem"><a href="#">Measurements</a></li>
		</ul>
		<li class="inactive">05 | more css</li>
		<li class="inactive">06 | CSS and SSIs</li>
		<li class="inactive">07 | template development</li>
		<li class="inactive">08 | more templating</li>
		<li class="inactive">09 | methodology</li>    
		<li class="inactive">10 | jQuery / Git</li>
	</ul>
</nav>
